"""Added following table

Revision ID: 381989bb5e9b
Revises: d7d07ecd7fa2
Create Date: 2024-11-23 12:02:11.469933

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '381989bb5e9b'
down_revision: Union[str, None] = 'd7d07ecd7fa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user_follow',
        sa.Column('follower_id', sa.Integer(), sa.ForeignKey('users.id', ondelete="CASCADE"), primary_key=True),
        sa.Column('following_id', sa.Integer(), sa.ForeignKey('users.id', ondelete="CASCADE"), primary_key=True),
    ) 


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_follow')
    # ### end Alembic commands ###
