from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e39ffb19b63c'
down_revision = '78b22330eb0f'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('users', sa.Column('role', sa.Enum('normal', 'admin', name='userrole'), nullable=False,
                                     server_default='normal'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove 'role' column from 'users' table
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
